import type { PrismaClient } from "@prisma/client";
import { logProgress } from "./helpers";

/**
 * Seeds the Knowledge Center content tables (Video, Article,
 * LearnTopic) with sample data matching the /knowledge redesign.
 *
 * Idempotent:
 * - Videos key on `videoId` (Prisma @unique) via upsert.
 * - Articles key on `articleUrl` via findFirst+create, so re-running
 *   doesn't duplicate rows.
 * - LearnTopics key on `title` within `category` via the same
 *   pattern.
 *
 * Content sources:
 * - Basics bodies: the rebuild's existing web/src/content/knowledge.json,
 *   carried over so the migration from static JSON → DB is a no-op
 *   visually on day one. FAQ + Myth Buster intentionally stay in the
 *   rebuild's JSON for now.
 * - Videos: TODO placeholders. Real IDs need to be pasted from the
 *   Ekush YouTube channel (UC0fw_pbgQjWy1ZlrvEd5EaA). Left with
 *   isPublished=false so placeholder rows don't leak to the public
 *   site before admin reviews.
 * - Articles: the three TBS/FE/TBS headlines from the Step-2 mock
 *   data (ekush-rebuild/web/src/content/knowledge-mock.ts).
 */

export async function seedKnowledgeCenter(prisma: PrismaClient) {
  logProgress("Seeding Knowledge Center content...");

  await seedLearnTopics(prisma);
  await seedArticles(prisma);
  await seedVideos(prisma);

  logProgress("Knowledge Center seed complete.");
}

// ─── LearnTopics ──────────────────────────────────────────────
async function seedLearnTopics(prisma: PrismaClient) {
  const topics: Array<{
    title: string;
    summary: string;
    body: string;
    iconKey: string;
    displayOrder: number;
  }> = [
    {
      title: "Mutual Fund and how it works",
      summary:
        "Read · 4 min · The pooling model, professional management, and returns",
      iconKey: "cube",
      displayOrder: 1,
      body:
        `<p>A mutual fund is a collective investment vehicle that gathers money from multiple investors&mdash;both individual and institutional&mdash;to invest in a diversified portfolio of assets such as stocks, bonds, and other securities. Managed by professional fund managers, mutual funds offer investors the benefits of diversification, expert management, and convenient access to a wide range of investment opportunities.</p>` +
        `<p>When investors contribute to a mutual fund, they receive units corresponding to the amount invested, making them <strong>unitholders</strong>. The profits or losses generated by the fund are distributed among unitholders in proportion to their investment. Before raising funds from the public, mutual funds are required to register with the Bangladesh Securities &amp; Exchange Commission (BSEC).</p>`,
    },
    {
      title: "Types of Mutual Fund on their structure",
      summary:
        "Read · 5 min · Open-end vs closed-end funds — which one suits you",
      iconKey: "layers",
      displayOrder: 2,
      body:
        `<h4>Open-Ended Mutual Funds</h4>` +
        `<p>With open-ended mutual funds, you can buy or sell your units any business day you wish. There's no minimum holding period. The price of each unit, known as Net Asset Value (NAV), is recalculated daily based on the fund's underlying investments. This gives investors the flexibility to subscribe or redeem whenever needed at the current NAV.</p>` +
        `<h4>Close-Ended Mutual Funds</h4>` +
        `<p>Close-ended funds have a fixed number of units and operate for a set period. You can only purchase units when the fund is initially launched; afterwards, units trade on the stock exchange like company shares. You cannot buy directly from or sell back to the fund during its term, and the market price may differ from NAV depending on supply and demand.</p>`,
    },
    {
      title: "Asset Management Company (AMC) and its role",
      summary:
        "Read · 3 min · What an AMC does, how it is regulated, how it earns fees",
      iconKey: "bank",
      displayOrder: 3,
      body:
        `<p>An Asset Management Company in Bangladesh is the BSEC-licensed institution responsible for managing mutual funds on behalf of investors. The AMC collects funds, makes investment decisions, manages the portfolio, and maximises risk-adjusted returns within each fund's stated objectives.</p>` +
        `<p>In exchange for professional management, the AMC charges a management fee&mdash;a small percentage of assets under management, disclosed transparently in the prospectus. AMCs are also responsible for regular reporting to unitholders and for administering unit issuance, transfers, and redemptions.</p>`,
    },
    {
      title: "NAV, SIP & SWP explained",
      summary:
        "Read · 6 min · Three essential acronyms every mutual fund investor must know",
      iconKey: "chart",
      displayOrder: 4,
      body:
        `<h4>Net Asset Value (NAV)</h4>` +
        `<p>NAV is the per-unit price of a fund, computed daily as <em>(total assets &minus; liabilities) &divide; units outstanding</em>. It's the rate at which you buy or redeem units. Rising NAV reflects a fund's portfolio gains; falling NAV, losses.</p>` +
        `<h4>SIP &mdash; Systematic Investment Plan</h4>` +
        `<p>A disciplined way to invest a fixed amount on a fixed schedule (usually monthly). You authorise auto-debits from your bank, and over time the recurring subscription accumulates units at varying NAVs&mdash;spreading entry price and dampening timing risk.</p>` +
        `<h4>SWP &mdash; Systematic Withdrawal Plan</h4>` +
        `<p>The reverse of SIP. You authorise fixed periodic redemptions (e.g. monthly) from your holding; the fund sells just enough units at current NAV to pay you the set amount. Useful for retirees or anyone wanting predictable cash flow.</p>`,
    },
  ];

  for (const t of topics) {
    const existing = await prisma.learnTopic.findFirst({
      where: { title: t.title, category: "basics" },
      select: { id: true },
    });
    if (existing) {
      await prisma.learnTopic.update({
        where: { id: existing.id },
        data: {
          summary: t.summary,
          body: t.body,
          iconKey: t.iconKey,
          displayOrder: t.displayOrder,
          isPublished: true,
        },
      });
    } else {
      await prisma.learnTopic.create({
        data: {
          title: t.title,
          summary: t.summary,
          body: t.body,
          iconKey: t.iconKey,
          category: "basics",
          displayOrder: t.displayOrder,
          isPublished: true,
        },
      });
    }
    logProgress(`  LearnTopic: ${t.title}`);
  }
}

// ─── Articles ────────────────────────────────────────────────
async function seedArticles(prisma: PrismaClient) {
  const articles: Array<{
    articleUrl: string;
    publisher: string;
    title: string;
    excerpt: string;
    coverImageUrl: string;
    category: string;
    publishedAt: Date;
    readTimeMinutes: number;
    displayOrder: number;
  }> = [
    {
      articleUrl: "https://www.tbsnews.net/",
      publisher: "tbs",
      title:
        "Why mutual funds are the missing piece for retail investors in Bangladesh",
      excerpt:
        "A closer look at why diversified fund products are essential infrastructure for a maturing capital market — and the role AMCs must play.",
      // Dark teal/green gradient placeholder until admin pastes a real OG image.
      coverImageUrl: "https://ekush.aibd.ai/placeholder-article-tbs.png",
      category: "opinion",
      publishedAt: new Date("2026-03-18"),
      readTimeMinutes: 6,
      displayOrder: 1,
    },
    {
      articleUrl: "https://thefinancialexpress.com.bd/",
      publisher: "financial_express",
      title:
        "Decoding NAV: what every first-time investor should understand",
      excerpt:
        'Net Asset Value is not the same as "cheap or expensive." Here is how to read it properly before subscribing to any fund.',
      coverImageUrl: "https://ekush.aibd.ai/placeholder-article-fe.png",
      category: "analysis",
      publishedAt: new Date("2026-02-05"),
      readTimeMinutes: 4,
      displayOrder: 2,
    },
    {
      articleUrl: "https://www.tbsnews.net/sip-culture",
      publisher: "tbs",
      title:
        "SIP culture: building long-term wealth, one small instalment at a time",
      excerpt:
        "Systematic Investment Plans are changing how middle-income households in Dhaka and Chattogram think about savings.",
      coverImageUrl: "https://ekush.aibd.ai/placeholder-article-sip.png",
      category: "feature",
      publishedAt: new Date("2026-01-22"),
      readTimeMinutes: 8,
      displayOrder: 3,
    },
  ];

  for (const a of articles) {
    const existing = await prisma.article.findFirst({
      where: { articleUrl: a.articleUrl },
      select: { id: true },
    });
    if (existing) {
      await prisma.article.update({
        where: { id: existing.id },
        data: { ...a, isPublished: true },
      });
    } else {
      await prisma.article.create({ data: { ...a, isPublished: true } });
    }
    logProgress(`  Article: ${a.title.slice(0, 60)}…`);
  }
}

// ─── Videos ───────────────────────────────────────────────────
async function seedVideos(prisma: PrismaClient) {
  // TODO: replace these placeholder IDs with real videos from
  // https://www.youtube.com/channel/UC0fw_pbgQjWy1ZlrvEd5EaA
  // Once the real IDs are in, the admin can hit "Refresh" on each
  // row to pull live thumbnails/title/duration/stats from the
  // YouTube Data API (Step 5).
  const videos: Array<{
    videoId: string;
    youtubeUrl: string;
    title: string;
    category: string;
    thumbnailUrl: string;
    duration: string;
    isFeatured: boolean;
    displayOrder: number;
  }> = [
    {
      videoId: "PLACEHOLD_01",
      youtubeUrl: "https://www.youtube.com/channel/UC0fw_pbgQjWy1ZlrvEd5EaA",
      title: "[SAMPLE] What is a Mutual Fund? Beginner's guide",
      category: "basics",
      thumbnailUrl: "https://ekush.aibd.ai/placeholder-video-1.png",
      duration: "14:32",
      isFeatured: true,
      displayOrder: 1,
    },
    {
      videoId: "PLACEHOLD_02",
      youtubeUrl: "https://www.youtube.com/channel/UC0fw_pbgQjWy1ZlrvEd5EaA",
      title: "[SAMPLE] How is NAV calculated?",
      category: "basics",
      thumbnailUrl: "https://ekush.aibd.ai/placeholder-video-2.png",
      duration: "06:18",
      isFeatured: false,
      displayOrder: 2,
    },
    {
      videoId: "PLACEHOLD_03",
      youtubeUrl: "https://www.youtube.com/channel/UC0fw_pbgQjWy1ZlrvEd5EaA",
      title: "[SAMPLE] SIP vs lump-sum investing",
      category: "strategy",
      thumbnailUrl: "https://ekush.aibd.ai/placeholder-video-3.png",
      duration: "08:45",
      isFeatured: false,
      displayOrder: 3,
    },
  ];

  const publishedAt = new Date("2026-01-01");
  const now = new Date();

  for (const v of videos) {
    await prisma.video.upsert({
      where: { videoId: v.videoId },
      update: {
        youtubeUrl: v.youtubeUrl,
        title: v.title,
        category: v.category,
        thumbnailUrl: v.thumbnailUrl,
        duration: v.duration,
        isFeatured: v.isFeatured,
        displayOrder: v.displayOrder,
        // Seeded rows stay unpublished until admin reviews and swaps
        // in real IDs — otherwise placeholder thumbnails would leak
        // to ekushwml.com.
        isPublished: false,
        lastSyncedAt: now,
      },
      create: {
        videoId: v.videoId,
        youtubeUrl: v.youtubeUrl,
        title: v.title,
        category: v.category,
        thumbnailUrl: v.thumbnailUrl,
        duration: v.duration,
        viewCount: 0,
        likeCount: 0,
        publishedAt,
        isFeatured: v.isFeatured,
        displayOrder: v.displayOrder,
        isPublished: false,
        lastSyncedAt: now,
      },
    });
    logProgress(`  Video (draft): ${v.title}`);
  }
}
